minecraft_version: "1.20.4"
asset_pack: "v1"
loaders: [fabric, neoforge]
java_version: 21
neoforge_version: "21.1.0"
forge_version: "51.0.0"
fabric_loader_version: "0.16.9"
fabric_api_version: "0.100.0"