# Renaming 1_20_1 to be 1_20_4 (NeoForge better supported)
# This file will be replaced
minecraft_version: "1.20.4"
asset_pack: "v1"

loaders:
  - fabric
  - forge
  - neoforge

java_version: 17

# Real versions for MC 1.20.4
neoforge_version: "20.4.238"  # Latest for 1.20.4
forge_version: "49.1.0"       # Latest Forge for 1.20.4
fabric_loader_version: "0.16.9"
fabric_api_version: "0.97.0+1.20.4"
